### ISSUE TITLE
chore: layout 패키지 설정

### ISSUE THREAD

**Issue by dev1week** [dev1week/DesignSystem#14]
## Description ✏
- layout 패키지를 설정합니다.

## Todo 📝
- [ ] vanilla extract 설치 
- [ ] 공용 css 만들기 
- [ ] react-components-layout 프로젝트 만들기
